name: Daily.Dev Card

on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * *"

jobs:
  dev-card:
    runs-on: ubuntu-latest
    steps:
      - name: Get Dev Card
        uses: dailydotdev/action-devcard@2.1.0
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}
